CREATE DATABASE blog
DEFAULT CHARACTER SET utf8;
USE blog;
CREATE TABLE usuarios(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(30) NOT NULL,
	email VARCHAR(255) NOT NULL,
	passwor VARCHAR(255)NOT NULL,
	fecha_registro DATETIME NOT NULL,
	activo TINYINT NOT NULL
);

CREATE TABLE  entradas (
	id INT NOT NULL  UNIQUE AUTO_INCREMENT,
	autor_id INT NOT NULL,
	itulo VARCHAR(250) NOT NULL UNIQUE,
	texto TEXT CHARACTER SET utf8 NOT NULL,
	fecha DATETIME NOT NULL,
	activa TINYINT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY (autor_id) REFERENCES usuarios(id)
		ON UPDATE CASCADE 
		ON DELETE RESTRICT 
);

CREATE TABLE comentarios(
	id INT NOT NULL AUTO_INCREMENT,
	autor_id INT NOT NULL,
	entrada_id INT NOT NULL,
	titulo VARCHAR(250) NOT NULL,
	texto TEXT CHARACTER SET utf8 NOT NULL,
	fecha DATETIME NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (autor_id) REFERENCES usuarios(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT,
	FOREIGN KEY (entrada_id) REFERENCES entradas(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
);

