CREATE DATABASE blog;
USE blog;
CREATE TABLE usuarios(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(30) NOT NULL,
	email VARCHAR(250) NOT NULL,
	passwor VARCHAR(40)NOT NULL,
	fecha_registro DATETIME NOT NULL,
	activo TINYINT NOT NULL
);

